# Generated by Django 4.2.3 on 2024-04-27 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOneSDG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='users_who_are_admins', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Corresponding user username')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipId', models.AutoField(primary_key=True, serialize=False, verbose_name='Equipment ID')),
                ('equipName', models.CharField(max_length=100, verbose_name='Equipment name')),
                ('equipType', models.CharField(max_length=100, verbose_name='Equipment type')),
                ('equipQuantity', models.IntegerField(default=0, verbose_name='Quantity for equipment')),
                ('equipAudit', models.DateField(verbose_name='Last audit for equipment')),
                ('equipLocation', models.CharField(max_length=100, verbose_name='Location of equipment')),
                ('equipStatus', models.CharField(blank=True, max_length=100, verbose_name='Status of equipment')),
                ('equipComments', models.TextField(blank=True, verbose_name='Comments on equipment')),
                ('isOnsite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Device_Serial_Number',
            fields=[
                ('equipId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='equipments_with_extra_details', serialize=False, to='AppOneSDG.equipment', verbose_name='Corresponding equipment ID')),
                ('deviceSerialNo', models.CharField(max_length=100, verbose_name='Device serial number')),
                ('deviceCPU', models.CharField(blank=True, max_length=100, verbose_name='Device CPU')),
                ('deviceGPU', models.CharField(blank=True, max_length=100, verbose_name='Device GPU')),
                ('deviceRAM', models.CharField(blank=True, max_length=100, verbose_name='Device RAM')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationId', models.AutoField(primary_key=True, serialize=False, verbose_name='Reservation ID')),
                ('reservationStatus', models.CharField(max_length=100, verbose_name='Status of reservation')),
                ('reservationDate', models.DateField(auto_now_add=True, verbose_name='Date of reservation')),
                ('returnDate', models.DateField(verbose_name='Return date for reservation')),
                ('reservationNotes', models.TextField(blank=True, verbose_name='Notes about reservation')),
                ('adminUserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins_who_approve_reservations', to='AppOneSDG.admin', verbose_name='Corresponding admin ID')),
                ('equipId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments_that_are_reserved', to='AppOneSDG.equipment', verbose_name='Corresponding equipment ID')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_who_place_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Corresponding user ID')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False, verbose_name='Booking ID')),
                ('bookingStartDate', models.DateField(verbose_name='Start date for booking')),
                ('bookingEndDate', models.DateField(verbose_name='End date for booking')),
                ('bookingStatus', models.CharField(max_length=100, verbose_name='Status of booking')),
                ('isOverdue', models.BooleanField(default=False)),
                ('adminUserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins_who_manage_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Corresponding admin ID')),
                ('reservationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_which_become_booked', to=settings.AUTH_USER_MODEL, verbose_name='Corresponding reservation ID')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alertId', models.AutoField(primary_key=True, serialize=False, verbose_name='Alert ID')),
                ('alertType', models.CharField(max_length=100, verbose_name='Alert type')),
                ('alertMessage', models.CharField(max_length=100, verbose_name='Alert message')),
                ('alertDate', models.DateTimeField(verbose_name='Date/Time of Alert')),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_which_trigger_alerts', to='AppOneSDG.booking', verbose_name='Corresponding booking ID')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_being_sent_alerts', to='AppOneSDG.admin', verbose_name='Corresponding user ID')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_User_Manage',
            fields=[
                ('modifyId', models.AutoField(primary_key=True, serialize=False, verbose_name='ID of this management')),
                ('modifyDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Time/Date of management')),
                ('adminUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins_who_manage_users', to='AppOneSDG.admin', verbose_name='Corresponding admin ID')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_who_admins_manage', to=settings.AUTH_USER_MODEL, verbose_name='Corresponding user ID')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_Equip_Manage',
            fields=[
                ('updateId', models.AutoField(primary_key=True, serialize=False, verbose_name='ID of this management')),
                ('updateDateTime', models.DateTimeField(auto_now_add=True, verbose_name='Time/Date of management')),
                ('adminUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins_who_manage_equipments', to='AppOneSDG.admin', verbose_name='Corresponding admin ID')),
                ('equipId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments_that_admins_manage', to='AppOneSDG.equipment', verbose_name='Corresponding equipment ID')),
            ],
        ),
    ]
